# Generated by Django 3.2.20 on 2023-08-09 23:26

from django.db import migrations

# populate_data function
def populate_data(apps, schema_editor):
    Staff = apps.get_model('book_a_treatment', 'Staff')
    Staff.objects.create(name='Eirini')
    Staff.objects.create(name='Ciara')
    Staff.objects.create(name='Vanessa')
    Staff.objects.create(name='Maria')

class Migration(migrations.Migration):

    dependencies = [
        ('book_a_treatment', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(populate_data, migrations.RunPython.noop),
    ]
