# Generated by Django 3.2.20 on 2023-08-09 22:46

from django.db import migrations

# populate_data function
def populate_data(apps, schema_editor):

    TreatmentType = apps.get_model('treatments', 'TreatmentType')
    Treatment = apps.get_model('treatments', 'Treatment')
    
    shellac_type = TreatmentType.objects.create(name='Shellac')
    gel_nails_type = TreatmentType.objects.create(name='Gel nails')
    manicure_type = TreatmentType.objects.create(name='Manicure')
    pedicure_type = TreatmentType.objects.create(name='Pedicure')

    #shellac treatments
    Treatment.objects.create(name='Shellac Manicure (new set)', price=25.0, treatmentType=shellac_type)
    Treatment.objects.create(name='Shellac Manicure (removal + new set)', price=28.0, treatmentType=shellac_type)
    Treatment.objects.create(name='Shellac Pedicure (new set)', price=30.0, treatmentType=shellac_type)
    Treatment.objects.create(name='Shellac Pedicure (removal + new set)', price=35.0, treatmentType=shellac_type)
    Treatment.objects.create(name='Shellac Manicure & Pedicure (removal)', price=12.0, treatmentType=shellac_type)

    #gel nail treatments
    Treatment.objects.create(name='Gel nails', price=48.0, treatmentType=gel_nails_type)
    Treatment.objects.create(name='Renewal (short nails)', price=40.0, treatmentType=gel_nails_type)
    Treatment.objects.create(name='Renewal (long nails)', price=45.0, treatmentType=gel_nails_type)
    Treatment.objects.create(name='One nail replacement', price=9.0, treatmentType=gel_nails_type)
    Treatment.objects.create(name='Full set (color or french)', price=60.0, treatmentType=gel_nails_type)
    Treatment.objects.create(name='Full set (color/french + pedi+shellac)', price=70.0, treatmentType=gel_nails_type)

    #manicure treatments
    Treatment.objects.create(name='Mini manicure + color', price=20.0, treatmentType=manicure_type)
    Treatment.objects.create(name='Full manicure + color', price=35.0, treatmentType=manicure_type)
    Treatment.objects.create(name='Full manicure + shellac', price=50.0, treatmentType=manicure_type)

    #pedicure treatments
    Treatment.objects.create(name='Mini pedicure + color', price=25.0, treatmentType=pedicure_type)
    Treatment.objects.create(name='Full pedicure + color', price=55.0, treatmentType=pedicure_type)
    Treatment.objects.create(name='Full pedicure + shellac', price=65.0, treatmentType=pedicure_type)


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data, migrations.RunPython.noop),
    ]
